export const GET_GAMES_REQUESTED = 'GET_GAMES_REQUESTED';
export const GET_GAMES_REJECTED = 'GET_GAMES_REJECTED';
export const GET_GAMES_FULFILLED = 'GET_GAMES_FULFILLED';

export const GET_PLAYERS_REQUESTED = 'GET_PLAYERS_REQUESTED';
export const GET_PLAYERS_REJECTED = 'GET_PLAYERS_REJECTED';
export const GET_PLAYERS_FULFILLED = 'GET_PLAYERS_FULFILLED';

export const GET_TEAMS_REQUESTED = 'GET_TEAMS_REQUESTED';
export const GET_TEAMS_REJECTED = 'GET_TEAMS_REJECTED';
export const GET_TEAMS_FULFILLED = 'GET_TEAMS_FULFILLED';
